version: '3'

services:
    user:
        build:
            context: .
        image: codelab/user
        depends_on:
            - user-db
        hostname: user
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - MONGO_HOST=user-db:27017
            - reschedule=on-node-failure
        ports:
            - "8080:8084"
    user-db:
        build:
            context: ./docker/user-db/
        image: codelab/user-db
        hostname: user-db
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        environment:
            - reschedule=on-node-failure
            - AUTH=no
            - MONGO_INITDB_DATABASE=db-users
        ports:
            - "27017:27017"
        volumes:
            - 'db:/data/db-users'
volumes:
  db:
